import type {
  DSA,
  BankEmployee,
  SystemStaff,
  Reminder,
} from "@/types";

// ── DSAs ──────────────────────────────────────────────────────────────────────
export const mockDSAs: DSA[] = [
  { id: "dsa-1", name: "Ramesh Babu",  phone: "9876543210", email: "ramesh@dsa.com",  region: "Hyderabad", totalLeads: 42, activeLeads: 8,  status: "Active"   },
  { id: "dsa-2", name: "Priya Sharma", phone: "9845012345", email: "priya@dsa.com",   region: "Bangalore", totalLeads: 36, activeLeads: 6,  status: "Active"   },
  { id: "dsa-3", name: "Kiran Reddy",  phone: "9900112233", email: "kiran@dsa.com",   region: "Chennai",   totalLeads: 29, activeLeads: 5,  status: "Active"   },
  { id: "dsa-4", name: "Sunita Rao",   phone: "9712345678", email: "sunita@dsa.com",  region: "Mumbai",    totalLeads: 18, activeLeads: 4,  status: "Active"   },
  { id: "dsa-5", name: "Vijay Kumar",  phone: "9123456789", email: "vijay@dsa.com",   region: "Pune",      totalLeads: 11, activeLeads: 0,  status: "Inactive" },
];

// ── Software Leads ────────────────────────────────────────────────────────────
export const mockLeads: any[] = [
  {
    id: "lead-1",
    fullName: "Rahul Verma",
    phone: "9876543210",
    email: "rahul.verma@gmail.com",
    loanType: "E-commerce Website",
    projectType: "App + Web Development",
    loanAmount: 2000000,
    source: "ADVERTISEMENT",
    status: "CONVERTED",
    followUp: false,
    notes: "Full-stack e-commerce platform with payment gateway, inventory management, and admin dashboard.",
    createdAt: "2026-05-01T09:00:00Z",
    updatedAt: "2026-05-10T11:00:00Z",
  },
  {
    id: "lead-2",
    fullName: "Sneha Patel",
    phone: "9845012345",
    email: "sneha.patel@gmail.com",
    loanType: "Mobile Banking App",
    projectType: "App Development",
    loanAmount: 5000000,
    source: "CLIENT_REFERENCE",
    status: "CONVERTED",
    followUp: false,
    notes: "Cross-platform mobile banking app with biometric login, UPI integration, and real-time notifications.",
    createdAt: "2026-05-05T10:00:00Z",
    updatedAt: "2026-05-15T14:00:00Z",
  },
  {
    id: "lead-3",
    fullName: "Arjun Nair",
    phone: "9900112233",
    email: "arjun.nair@gmail.com",
    loanType: "HR Management System",
    projectType: "Web Development",
    loanAmount: 800000,
    source: "SALES_EXECUTIVE",
    status: "PENDING",
    followUp: true,
    notes: "HRMS covering recruitment, payroll, attendance, and performance management for 500+ employees.",
    createdAt: "2026-05-10T08:00:00Z",
    updatedAt: "2026-05-10T08:00:00Z",
  },
  {
    id: "lead-4",
    fullName: "Divya Krishnan",
    phone: "9712345678",
    email: "divya.k@gmail.com",
    loanType: "Healthcare Portal",
    projectType: "Web Development",
    loanAmount: 300000,
    source: "ADVERTISEMENT",
    status: "REJECTED",
    followUp: false,
    notes: "Patient management portal with appointment scheduling and medical records. Budget insufficient for scope.",
    createdAt: "2026-04-20T11:00:00Z",
    updatedAt: "2026-04-25T16:00:00Z",
  },
  {
    id: "lead-5",
    fullName: "Mohammed Irfan",
    phone: "9123456789",
    email: "irfan.m@gmail.com",
    loanType: "Real Estate Platform",
    projectType: "App + Web Development",
    loanAmount: 8000000,
    source: "CLIENT_REFERENCE",
    status: "CONVERTED",
    followUp: false,
    notes: "Property listing and management platform with virtual tours, agent CRM, and EMI calculator.",
    createdAt: "2026-04-01T09:00:00Z",
    updatedAt: "2026-04-20T10:00:00Z",
  },
  {
    id: "lead-6",
    fullName: "Lakshmi Devi",
    phone: "9654321098",
    email: "lakshmi.d@gmail.com",
    loanType: "School Management System",
    projectType: "Web Development",
    loanAmount: 200000,
    source: "SALES_EXECUTIVE",
    status: "PENDING",
    followUp: true,
    notes: "School ERP with admissions, fee management, timetable, and parent communication module.",
    createdAt: "2026-05-12T10:00:00Z",
    updatedAt: "2026-05-12T10:00:00Z",
  },
  {
    id: "lead-7",
    fullName: "Suresh Goud",
    phone: "9543210987",
    email: "suresh.g@gmail.com",
    loanType: "Hospital Information System",
    projectType: "Web Development",
    loanAmount: 1500000,
    source: "ADVERTISEMENT",
    status: "PENDING",
    followUp: false,
    notes: "Complete HIS with OPD/IPD management, pharmacy, lab, and billing for a 200-bed hospital.",
    createdAt: "2026-05-08T07:00:00Z",
    updatedAt: "2026-05-14T09:00:00Z",
  },
  {
    id: "lead-8",
    fullName: "Anita Reddy",
    phone: "9432109876",
    email: "anita.r@gmail.com",
    loanType: "CRM Software",
    projectType: "Web Development",
    loanAmount: 3000000,
    source: "CLIENT_REFERENCE",
    status: "PENDING",
    followUp: false,
    notes: "Custom CRM for B2B sales team with pipeline tracking, email integration, and reporting dashboard.",
    createdAt: "2026-05-13T11:00:00Z",
    updatedAt: "2026-05-13T11:00:00Z",
  },
  {
    id: "lead-9",
    fullName: "Prakash Rao",
    phone: "9321098765",
    email: "prakash.r@gmail.com",
    loanType: "Inventory Management System",
    projectType: "Web Development",
    loanAmount: 500000,
    source: "SALES_EXECUTIVE",
    status: "PENDING",
    followUp: false,
    notes: "Multi-warehouse inventory system with barcode scanning, reorder alerts, and supplier management.",
    createdAt: "2026-05-03T08:00:00Z",
    updatedAt: "2026-05-09T10:00:00Z",
  },
  {
    id: "lead-10",
    fullName: "Kavitha Menon",
    phone: "9210987654",
    email: "kavitha.m@gmail.com",
    loanType: "Learning Management System",
    projectType: "App + Web Development",
    loanAmount: 4000000,
    source: "ADVERTISEMENT",
    status: "CONVERTED",
    followUp: false,
    notes: "Online learning platform with video courses, quizzes, certificates, and live class support.",
    createdAt: "2026-03-15T09:00:00Z",
    updatedAt: "2026-04-01T11:00:00Z",
  },
];

// ── Projects (from converted leads) ──────────────────────────────────────────
export const mockProjects: any[] = [
  {
    id: "proj-1",
    leadId: "lead-1",
    customerId: "cust-1",
    clientName: "Rahul Verma",
    phone: "9876543210",
    email: "rahul.verma@gmail.com",
    projectName: "E-commerce Website",
    projectType: "App + Web Development",
    budget: 2000000,
    description: "Full-stack e-commerce platform with payment gateway, inventory management, and admin dashboard.",
    contractNumber: "APP-202605-R1V8",
    status: "Active",
    createdAt: "2026-05-10T11:00:00Z",
    updatedAt: "2026-05-10T11:00:00Z",
    payments: [
      { id: "pay-m1", amount: 500000, mode: "Bank Transfer", date: "2026-05-12", note: "Advance payment", createdAt: "2026-05-12T10:30:00Z" },
      { id: "pay-m2", amount: 750000, mode: "UPI",           date: "2026-05-20", note: "Milestone 1",     createdAt: "2026-05-20T14:15:00Z" },
    ],
  },
  {
    id: "proj-2",
    leadId: "lead-2",
    customerId: "cust-2",
    clientName: "Sneha Patel",
    phone: "9845012345",
    email: "sneha.patel@gmail.com",
    projectName: "Mobile Banking App",
    projectType: "App Development",
    budget: 5000000,
    description: "Cross-platform mobile banking app with biometric login, UPI integration, and real-time notifications.",
    contractNumber: "APP-202605-S2P4",
    status: "Completed",
    createdAt: "2026-05-15T14:00:00Z",
    updatedAt: "2026-05-20T10:00:00Z",
    payments: [
      { id: "pay-s1", amount: 1500000, mode: "Cheque",        date: "2026-05-16", note: "Initial advance", createdAt: "2026-05-16T09:00:00Z" },
      { id: "pay-s2", amount: 2000000, mode: "Bank Transfer", date: "2026-05-18", note: "Phase 2",          createdAt: "2026-05-18T11:30:00Z" },
      { id: "pay-s3", amount: 1500000, mode: "UPI",           date: "2026-05-20", note: "Final payment",    createdAt: "2026-05-20T16:00:00Z" },
    ],
  },
  {
    id: "proj-3",
    leadId: "lead-5",
    customerId: "cust-1",
    clientName: "Mohammed Irfan",
    phone: "9123456789",
    email: "irfan.m@gmail.com",
    projectName: "Real Estate Platform",
    projectType: "App + Web Development",
    budget: 8000000,
    description: "Property listing and management platform with virtual tours, agent CRM, and EMI calculator.",
    contractNumber: "APP-202604-H3K9",
    status: "Active",
    createdAt: "2026-04-20T10:00:00Z",
    updatedAt: "2026-04-20T10:00:00Z",
    payments: [
      { id: "pay-i1", amount: 2000000, mode: "Bank Transfer", date: "2026-04-22", note: "Advance 25%",  createdAt: "2026-04-22T10:00:00Z" },
      { id: "pay-i2", amount: 1500000, mode: "Cheque",        date: "2026-05-05", note: "Milestone 1",  createdAt: "2026-05-05T12:45:00Z" },
    ],
  },
  {
    id: "proj-4",
    leadId: "lead-10",
    customerId: "cust-2",
    clientName: "Kavitha Menon",
    phone: "9210987654",
    email: "kavitha.m@gmail.com",
    projectName: "Learning Management System",
    projectType: "App + Web Development",
    budget: 4000000,
    description: "Online learning platform with video courses, quizzes, certificates, and live class support.",
    contractNumber: "APP-202604-M7P2",
    status: "On Hold",
    createdAt: "2026-04-01T11:00:00Z",
    updatedAt: "2026-04-15T09:00:00Z",
    payments: [
      { id: "pay-k1", amount: 1000000, mode: "UPI", date: "2026-04-03", note: "Booking amount", createdAt: "2026-04-03T09:30:00Z" },
    ],
  },
];

// ── Customers (from converted leads) ─────────────────────────────────────────
export const mockCustomers = [
  {
    id: "cust-1",
    leadId: "lead-5",
    name: "Mohammed Irfan",
    fullName: "Mohammed Irfan",
    phone: "9123456789",
    email: "irfan.m@gmail.com",
    loanType: "Real Estate Platform",
    projectType: "App + Web Development",
    loanAmount: 8000000,
    bankName: "",
    smName: "",
    smNumber: "",
    applicationNumber: "APP-202604-H3K9",
    status: "Active",
    createdAt: "2026-04-20T10:00:00Z",
  },
  {
    id: "cust-2",
    leadId: "lead-10",
    name: "Kavitha Menon",
    fullName: "Kavitha Menon",
    phone: "9210987654",
    email: "kavitha.m@gmail.com",
    loanType: "Learning Management System",
    projectType: "App + Web Development",
    loanAmount: 4000000,
    bankName: "",
    smName: "",
    smNumber: "",
    applicationNumber: "APP-202604-M7P2",
    status: "Active",
    createdAt: "2026-04-01T11:00:00Z",
  },
];

// ── Lead Reminders ────────────────────────────────────────────────────────────
export const mockLeadReminders: any[] = [
  {
    id: "lr-1",
    leadId: "lead-3",
    reminderAt: "2026-06-15T10:00:00Z",
    note: "Follow up on project requirements document and timeline",
    status: "PENDING",
    createdAt: "2026-06-09T09:00:00Z",
    updatedAt: "2026-06-09T09:00:00Z",
  },
  {
    id: "lr-2",
    leadId: "lead-3",
    reminderAt: "2026-06-01T11:00:00Z",
    note: "Initial call — client interested in HRMS. Will share FRS next week.",
    status: "DONE",
    createdAt: "2026-05-28T09:00:00Z",
    updatedAt: "2026-06-01T11:30:00Z",
  },
  {
    id: "lr-3",
    leadId: "lead-6",
    reminderAt: "2026-06-20T14:00:00Z",
    note: "Collect final scope document and approval from principal",
    status: "PENDING",
    createdAt: "2026-06-09T10:00:00Z",
    updatedAt: "2026-06-09T10:00:00Z",
  },
];

// ── Developers ───────────────────────────────────────────────────────────────
export const mockDevelopers: any[] = [
  {
    id: "dev-1",
    name: "Arun Sharma",
    phone: "9876501234",
    email: "arun.sharma@softleads.com",
    role: "Full Stack Developer",
    experience: "Senior (5–8 yrs)",
    skills: ["Frontend Development", "Backend Development", "Database Management", "API Development"],
    status: "Active",
    joinedAt: "2023-01-15",
    createdAt: "2023-01-15T09:00:00Z",
  },
  {
    id: "dev-2",
    name: "Priyanka Nair",
    phone: "9845098765",
    email: "priyanka.nair@softleads.com",
    role: "Frontend Developer",
    experience: "Mid-Level (3–5 yrs)",
    skills: ["Frontend Development", "UI/UX Design", "Mobile Development"],
    status: "Active",
    joinedAt: "2023-06-01",
    createdAt: "2023-06-01T09:00:00Z",
  },
  {
    id: "dev-3",
    name: "Rahul Desai",
    phone: "9900223344",
    email: "rahul.desai@softleads.com",
    role: "Backend Developer",
    experience: "Senior (5–8 yrs)",
    skills: ["Backend Development", "Database Management", "Server Maintenance", "Cloud Services"],
    status: "Active",
    joinedAt: "2022-09-10",
    createdAt: "2022-09-10T09:00:00Z",
  },
  {
    id: "dev-4",
    name: "Meena Krishnan",
    phone: "9712233445",
    email: "meena.k@softleads.com",
    role: "Database Administrator",
    experience: "Lead / Architect (8–12 yrs)",
    skills: ["Database Management", "Server Maintenance", "Cloud Services", "Cybersecurity"],
    status: "Active",
    joinedAt: "2021-03-20",
    createdAt: "2021-03-20T09:00:00Z",
  },
  {
    id: "dev-5",
    name: "Vikram Joshi",
    phone: "9123344556",
    email: "vikram.j@softleads.com",
    role: "DevOps Engineer",
    experience: "Mid-Level (3–5 yrs)",
    skills: ["DevOps / CI/CD", "Server Maintenance", "Cloud Services", "Cybersecurity"],
    status: "Active",
    joinedAt: "2024-02-01",
    createdAt: "2024-02-01T09:00:00Z",
  },
  {
    id: "dev-6",
    name: "Snehal Patil",
    phone: "9654455667",
    email: "snehal.p@softleads.com",
    role: "Mobile Developer",
    experience: "Junior (1–3 yrs)",
    skills: ["Mobile Development", "Frontend Development", "API Development"],
    status: "Active",
    joinedAt: "2024-08-15",
    createdAt: "2024-08-15T09:00:00Z",
  },
  {
    id: "dev-7",
    name: "Deepak Rao",
    phone: "9543566778",
    email: "deepak.r@softleads.com",
    role: "QA Engineer",
    experience: "Mid-Level (3–5 yrs)",
    skills: ["QA / Testing", "API Development", "Cybersecurity"],
    status: "Inactive",
    joinedAt: "2022-11-01",
    createdAt: "2022-11-01T09:00:00Z",
  },
];

// ── Bank Employees ────────────────────────────────────────────────────────────
export const mockBankEmployees: BankEmployee[] = [
  { id: "be-1", name: "Sanjay Kulkarni", phone: "9200000001", email: "sanjay.k@sbi.co.in",    bankName: "State Bank of India", branch: "Fort, Mumbai",              designation: "Branch Manager",       status: "Active"   },
  { id: "be-2", name: "Alka Mehrotra",   phone: "9200000002", email: "alka.m@hdfc.com",        bankName: "HDFC Bank",           branch: "Bandra, Mumbai",             designation: "Loan Officer",          status: "Active"   },
  { id: "be-3", name: "Tarun Malhotra",  phone: "9200000003", email: "tarun.m@icici.com",      bankName: "ICICI Bank",          branch: "Koramangala, Bangalore",     designation: "Senior Loan Officer",  status: "Active"   },
  { id: "be-4", name: "Reena Saxena",    phone: "9200000004", email: "reena.s@axis.com",       bankName: "Axis Bank",           branch: "Viman Nagar, Pune",          designation: "Credit Analyst",       status: "Inactive" },
  { id: "be-5", name: "Gaurav Bansal",   phone: "9200000005", email: "gaurav.b@bob.in",        bankName: "Bank of Baroda",      branch: "Navrangpura, Ahmedabad",     designation: "Relationship Manager", status: "Active"   },
];

// ── System Staff ──────────────────────────────────────────────────────────────
export const mockSystemStaff: SystemStaff[] = [
  { id: "ss-1", name: "Aditya Kapoor",    phone: "9300000001", email: "aditya.kapoor@softleads.com",    role: "Admin",        status: "Active",   joinedAt: "2022-01-10" },
  { id: "ss-2", name: "Manisha Trivedi",  phone: "9300000002", email: "manisha.trivedi@softleads.com",  role: "Manager",      status: "Active",   joinedAt: "2022-06-15" },
  { id: "ss-3", name: "Sandeep Roy",      phone: "9300000003", email: "sandeep.roy@softleads.com",      role: "Loan Officer", status: "Active",   joinedAt: "2023-03-01" },
  { id: "ss-4", name: "Poornima Iyer",    phone: "9300000004", email: "poornima.iyer@softleads.com",    role: "Loan Officer", status: "Active",   joinedAt: "2023-07-20" },
  { id: "ss-5", name: "Harsh Vardhan",    phone: "9300000005", email: "harsh.v@softleads.com",          role: "Loan Officer", status: "Inactive", joinedAt: "2023-11-05" },
];

// ── Reminders ─────────────────────────────────────────────────────────────────
export const mockReminders: Reminder[] = [
  { id: "rem-1", title: "Follow up with Arjun Nair",    description: "Share project timeline and get sign-off on requirements.",  dueDate: "2026-06-15", relatedTo: "Arjun Nair",    type: "Follow-up", status: "Pending", priority: "High"   },
  { id: "rem-2", title: "Proposal — Anita Reddy",       description: "Send final CRM proposal with revised pricing.",             dueDate: "2026-06-18", relatedTo: "Anita Reddy",   type: "Document",  status: "Pending", priority: "High"   },
  { id: "rem-3", title: "Follow up — Lakshmi Devi",     description: "Collect approval for school management system scope.",      dueDate: "2026-06-20", relatedTo: "Lakshmi Devi",  type: "Follow-up", status: "Pending", priority: "Medium" },
  { id: "rem-4", title: "Demo — Suresh Goud",           description: "Schedule product demo for hospital information system.",    dueDate: "2026-06-22", relatedTo: "Suresh Goud",   type: "Meeting",   status: "Pending", priority: "Medium" },
  { id: "rem-5", title: "Contract — Divya K.",          description: "Re-engage after budget revision next quarter.",             dueDate: "2026-09-01", relatedTo: "Divya Krishnan",type: "Follow-up", status: "Pending", priority: "Low"    },
  { id: "rem-6", title: "Go-live — Sneha Patel",        description: "Mobile banking app go-live support and UAT sign-off.",      dueDate: "2026-05-20", relatedTo: "Sneha Patel",   type: "Document",  status: "Done",    priority: "Medium" },
  { id: "rem-7", title: "Handover — Rahul Verma",       description: "E-commerce website final handover and training session.",   dueDate: "2026-05-12", relatedTo: "Rahul Verma",   type: "Document",  status: "Done",    priority: "Low"    },
];

// ── Documents (per lead / customer) ──────────────────────────────────────────
export const mockDocuments: Record<string, any[]> = {};
export const mockFollowUps: Record<string, any[]> = {};

// ── Tasks ─────────────────────────────────────────────────────────────────────
export const mockTasks: any[] = [
  { id: "task-1", title: "Design homepage UI", description: "Create wireframes and hi-fi designs for the homepage.", assignedTo: "dev-2", projectId: "proj-1", dueDate: "2026-06-15", priority: "High",   status: "In Progress", createdAt: "2026-06-01T09:00:00Z", updatedAt: "2026-06-01T09:00:00Z" },
  { id: "task-2", title: "Set up CI/CD pipeline", description: "Configure GitHub Actions with auto-deploy to staging.", assignedTo: "dev-5", projectId: "proj-1", dueDate: "2026-06-18", priority: "Medium", status: "Todo",        createdAt: "2026-06-02T10:00:00Z", updatedAt: "2026-06-02T10:00:00Z" },
  { id: "task-3", title: "Build REST API endpoints", description: "Develop product listing, cart, and checkout APIs.", assignedTo: "dev-3", projectId: "proj-1", dueDate: "2026-06-20", priority: "High",   status: "In Progress", createdAt: "2026-06-03T09:00:00Z", updatedAt: "2026-06-03T09:00:00Z" },
  { id: "task-4", title: "Database schema design", description: "Design and optimise PostgreSQL schema for banking app.", assignedTo: "dev-4", projectId: "proj-2", dueDate: "2026-05-10", priority: "Urgent", status: "Done",        createdAt: "2026-05-01T09:00:00Z", updatedAt: "2026-05-10T15:00:00Z" },
  { id: "task-5", title: "Mobile app authentication", description: "Implement biometric login and OTP flow.", assignedTo: "dev-6", projectId: "proj-2", dueDate: "2026-05-18", priority: "High",   status: "Done",        createdAt: "2026-05-05T09:00:00Z", updatedAt: "2026-05-18T12:00:00Z" },
  { id: "task-6", title: "Write unit tests", description: "Cover all API endpoints with Jest unit tests.", assignedTo: "dev-7", projectId: "proj-3", dueDate: "2026-06-25", priority: "Medium", status: "Todo",        createdAt: "2026-06-05T09:00:00Z", updatedAt: "2026-06-05T09:00:00Z" },
  { id: "task-7", title: "Deploy to production", description: "Final deployment and post-go-live monitoring.", assignedTo: "dev-1", projectId: "proj-3", dueDate: "2026-07-01", priority: "Urgent", status: "Todo",        createdAt: "2026-06-06T09:00:00Z", updatedAt: "2026-06-06T09:00:00Z" },
];

// ── Subscriptions ─────────────────────────────────────────────────────────────
export const mockSubscriptions: any[] = [
  { id: "sub-1", name: "softleads.in",       description: "Primary business domain.",             category: "Domain",               amount: 1200,  billingCycle: "Yearly",  renewalDate: "2027-03-10", status: "Active",    createdAt: "2026-03-10T09:00:00Z", updatedAt: "2026-03-10T09:00:00Z" },
  { id: "sub-2", name: "AWS EC2 t3.medium",  description: "Main production web server.",          category: "Hosting",              amount: 8500,  billingCycle: "Monthly", renewalDate: "2026-07-01", status: "Active",    createdAt: "2025-07-01T09:00:00Z", updatedAt: "2025-07-01T09:00:00Z" },
  { id: "sub-3", name: "Let's Encrypt SSL",  description: "Auto-renewing SSL for main domain.",   category: "SSL",                  amount: 0,    billingCycle: "Yearly",  renewalDate: "2026-09-01", status: "Active",    createdAt: "2025-09-01T09:00:00Z", updatedAt: "2025-09-01T09:00:00Z" },
  { id: "sub-4", name: "Monthly Server AMC", description: "Server uptime & patch maintenance.",   category: "Maintenance",          amount: 5000,  billingCycle: "Monthly", renewalDate: "2026-07-01", status: "Active",    createdAt: "2026-01-01T09:00:00Z", updatedAt: "2026-01-01T09:00:00Z" },
  { id: "sub-5", name: "GitHub Teams",       description: "Code repo and CI/CD pipelines.",       category: "Software Subscription", amount: 4000, billingCycle: "Monthly", renewalDate: "2026-07-15", status: "Active",    createdAt: "2025-07-15T09:00:00Z", updatedAt: "2025-07-15T09:00:00Z" },
  { id: "sub-6", name: "Figma Professional", description: "UI/UX design and prototyping.",        category: "Software Subscription", amount: 3500, billingCycle: "Monthly", renewalDate: "2026-06-20", status: "Active",    createdAt: "2025-06-20T09:00:00Z", updatedAt: "2025-06-20T09:00:00Z" },
  { id: "sub-7", name: "client-project.com", description: "Domain for Rahul Verma project.",      category: "Domain",               amount: 900,  billingCycle: "Yearly",  renewalDate: "2026-08-22", status: "Active",    createdAt: "2025-08-22T09:00:00Z", updatedAt: "2025-08-22T09:00:00Z" },
];
